# Generated by Django 3.2.7 on 2021-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_board_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
