# Generated by Django 3.2.7 on 2021-09-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210914_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color',
        ),
        migrations.RemoveField(
            model_name='card',
            name='priority',
        ),
    ]
