# Generated by Django 3.2.7 on 2021-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('white', 'WHITE'), ('green', 'GREEN')], default='green', max_length=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('to do', 'TO DO'), ('in progress', 'IN PROGRESS'), ('completed', 'COMPLETED'), ('done', 'DONE')], default='to do', max_length=11),
        ),
    ]
