# Generated by Django 3.2.7 on 2021-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210915_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('white', 'WHITE'), ('red', 'RED')], default='green', max_length=6),
        ),
    ]
