# Generated by Django 3.2.7 on 2021-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('white', 'WHITE'), ('green', 'GREEN')], default='white', editable=False, max_length=6),
        ),
    ]
