# Generated by Django 3.2.7 on 2021-09-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('red', 'RED'), ('white', 'WHITE')], default='white', max_length=6),
        ),
    ]
