# Generated by Django 3.2.7 on 2021-09-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
